/**
 * electron-builder afterPack hook. Runs after the app folder is packed and BEFORE the
 * installers / packages are built from it.
 *
 * Windows: embeds the Emir Code icon and version information into EmirCode.exe.
 * `win.signAndEditExecutable` is false because electron-builder's own resource editing needs
 * the winCodeSign archive, whose macOS symlinks cannot be extracted on Windows without
 * Developer Mode. Editing the exe only after the build (the old postbuild step) changed
 * release/win-unpacked alone, so installed and portable copies kept Electron's icon — in the
 * taskbar, on shortcuts and in Explorer.
 *
 * Linux: puts a small launcher script in front of the Electron binary (see LINUX_LAUNCHER).
 */
const { execFileSync } = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');

function cacheDir() {
  if (process.env.ELECTRON_BUILDER_CACHE) return process.env.ELECTRON_BUILDER_CACHE;
  if (process.platform === 'win32') return path.join(process.env.LOCALAPPDATA || os.homedir(), 'electron-builder', 'Cache');
  if (process.platform === 'darwin') return path.join(os.homedir(), 'Library', 'Caches', 'electron-builder');
  return path.join(os.homedir(), '.cache', 'electron-builder');
}

/** rcedit-x64.exe from electron-builder's winCodeSign cache (also from partially extracted copies). */
function findCachedRcedit() {
  if (process.env.RCEDIT_PATH && fs.existsSync(process.env.RCEDIT_PATH)) return process.env.RCEDIT_PATH;
  const base = path.join(cacheDir(), 'winCodeSign');
  if (!fs.existsSync(base)) return null;
  for (const entry of fs.readdirSync(base)) {
    const candidate = path.join(base, entry, 'rcedit-x64.exe');
    if (fs.existsSync(candidate)) return candidate;
  }
  return null;
}

async function findRcedit() {
  const cached = findCachedRcedit();
  if (cached) return cached;
  try {
    // Downloads winCodeSign into the cache. Without symlink rights the extraction reports an
    // error for the macOS symlinks, but rcedit-x64.exe has been extracted by then.
    const { getBin } = require('app-builder-lib/out/binDownload');
    const dir = await getBin('winCodeSign');
    const candidate = path.join(dir, 'rcedit-x64.exe');
    if (fs.existsSync(candidate)) return candidate;
  } catch {
    // fall through to the cache scan
  }
  return findCachedRcedit();
}

/**
 * Chromium's sandbox needs a root-owned SUID chrome-sandbox or unprivileged user namespaces.
 * Ubuntu 23.10+ restricts user namespaces with AppArmor, and AppImage / tar.gz copies cannot
 * have a SUID helper, so the plain binary exits at startup there ("The SUID sandbox helper
 * binary was found, but is not configured correctly"). The launcher keeps the sandbox wherever
 * it works and adds --no-sandbox only where it cannot start.
 */
const LINUX_LAUNCHER = (binName) => `#!/bin/sh
# Emir Code launcher (generated by scripts/afterPack.js).
HERE="$(dirname "$(readlink -f "$0")")"
BIN="$HERE/${binName}"

sandbox_usable() {
  helper="$HERE/chrome-sandbox"
  if [ -u "$helper" ] && [ "$(stat -c %u "$helper" 2>/dev/null)" = "0" ]; then
    return 0
  fi
  if [ "$(cat /proc/sys/kernel/apparmor_restrict_unprivileged_userns 2>/dev/null)" = "1" ]; then
    return 1
  fi
  if [ "$(cat /proc/sys/kernel/unprivileged_userns_clone 2>/dev/null)" = "0" ]; then
    return 1
  fi
  command -v unshare >/dev/null 2>&1 && unshare --user --map-root-user true >/dev/null 2>&1
}

if [ -n "$EMIR_CODE_FORCE_SANDBOX" ] || sandbox_usable; then
  exec "$BIN" "$@"
fi
exec "$BIN" --no-sandbox "$@"
`;

function wrapLinuxExecutable(context) {
  const exeName = context.packager.executableName || context.packager.appInfo.productFilename;
  const exe = path.join(context.appOutDir, exeName);
  const binName = `${exeName}-bin`;
  const bin = path.join(context.appOutDir, binName);
  if (!fs.existsSync(exe)) throw new Error(`afterPack: ${exe} not found`);
  const head = Buffer.alloc(32);
  const fd = fs.openSync(exe, 'r');
  fs.readSync(fd, head, 0, head.length, 0);
  fs.closeSync(fd);
  if (head.toString('latin1').startsWith('#!/bin/sh\n# Emir Code')) return; // already wrapped
  fs.rmSync(bin, { force: true });
  fs.renameSync(exe, bin);
  fs.writeFileSync(exe, LINUX_LAUNCHER(binName), { mode: 0o755 });
  fs.chmodSync(exe, 0o755);
  console.log(`  • afterPack: ${exeName} is now a launcher script for ${binName} (sandbox fallback)`);
}

exports.default = async function afterPack(context) {
  if (context.electronPlatformName === 'linux') {
    wrapLinuxExecutable(context);
    return;
  }
  if (context.electronPlatformName !== 'win32') return;

  const appInfo = context.packager.appInfo;
  const exeName = `${appInfo.productFilename}.exe`;
  const exe = path.join(context.appOutDir, exeName);
  const icon = path.join(__dirname, '..', 'build', 'icon.ico');
  if (!fs.existsSync(exe)) throw new Error(`afterPack: ${exe} not found`);

  const rcedit = await findRcedit();
  if (!rcedit) {
    throw new Error('afterPack: rcedit-x64.exe not found; the installer would ship with the Electron icon');
  }

  const version = appInfo.version;
  execFileSync(
    rcedit,
    [
      exe,
      '--set-icon', icon,
      '--set-version-string', 'FileDescription', 'Emir Code',
      '--set-version-string', 'ProductName', appInfo.productName,
      '--set-version-string', 'CompanyName', appInfo.companyName || 'Agah Emir',
      '--set-version-string', 'LegalCopyright', appInfo.copyright || 'Copyright (C) 2026 Agah Emir',
      '--set-version-string', 'InternalName', appInfo.productFilename,
      '--set-version-string', 'OriginalFilename', exeName,
      '--set-file-version', version,
      '--set-product-version', version,
    ],
    { stdio: 'inherit' }
  );
  console.log(`  • afterPack: embedded Emir Code icon and version ${version} into ${exeName}`);
};
